--- 
title: "Women's and Minorities' Working Opportunities in New York City from 1850 to 1940"
author: "Luwei Zhang, Guangyu Wu, Jingxiang Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

```{r include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE)
knitr::write_bib("knitr", file = "packages.bib")
```

At the turn of the 20th century, New York City experienced one of the fastest periods of urban growth, as it overtook London to become the most populous urbanized area in the world and the first mega-city in the human history ^["New York Urbanized Area: Population & Density from 1800 (Provisional)". Demographia. Retrieved July 8, 2009.]. Powering this tremendous growth is the working people of NYC, who came from different backgrounds and contributed to the booming industries of the city. 

However, working opportunities are not always abundant. The fierce competition between disadvantaged groups such as the Irish immigrants and the Black population escalates to one of the worst riots in American history ^[Harris, Leslie M. (2003). "The New York City Draft Riots". In the Shadow of Slavery: African Americans in New York City, 1626–1863. University of Chicago Press. Excerpted from pages 279–288. ISBN 9780226317755.]. In the meantime, women are also joining the labor force though their choices are much more limited than their male counterparts ^[Women at work: New York City at the turn of the 20th century. OUPblog. Retrieved December 13, 2021, from https://blog.oup.com/2017/10/women-work-new-york-city-turn-20th-century/]. 

In this project, we decide to study the working opportunities of disadvantaged groups in New York City from 1850 to 1940, as a review of an important historical period of NYC and a lesson for urbanizing cities in today's world. We will explore the working life of disadvantaged groups, i.e. females, minority ethnicity through a series of visualizations. By joining the demographic and occupational information, we seek to exhibit and explain the trends in working opportunities of the minorities. 

